name: healthmate_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # navigation
  go_router: ^17.1.0
  # state management
  flutter_riverpod: ^2.4.10
  # ui
  flutter_screenutil: ^5.9.3
  # icon
  lucide_icons: ^0.257.0
  # font
  google_fonts: ^8.0.2
  # local storage
  shared_preferences: ^2.5.3
  # svg
  flutter_svg: ^2.2.1
  # dio for http requests
  dio: ^5.9.0
  # retrofit for api client
  retrofit: ^4.9.0
  # environment variables
  flutter_dotenv: ^6.0.0
  # heroicons
  heroicons: ^0.11.0
  # pin input
  pinput: ^5.0.2
  # shimmer
  shimmer: ^3.0.0
  # easy localization
  easy_localization: ^3.0.8
  # google sign in
  google_sign_in: ^7.2.0
  # firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  # push notification
  flutter_local_notifications: ^19.5.0

  # scanning & image processing
  google_mlkit_text_recognition: ^0.14.0
  # image picker
  image_picker: ^1.1.2
  # permission handler
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  retrofit_generator: ^10.0.1
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  assets:
    - .env

    - assets/icons/
    - assets/icons/app/
    - assets/icons/auth/
    - assets/icons/popup/
    - assets/icons/home/
    - assets/icons/setting/

    - assets/images/
    - assets/images/onboarding/
    - assets/images/user/
    - assets/images/health/
    - assets/images/scan/

    - assets/lang/

    - assets/fonts/

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
        - asset: assets/fonts/Inter.ttf
          weight: 300
        - asset: assets/fonts/Inter.ttf
          weight: 400
        - asset: assets/fonts/Inter.ttf
          weight: 500
        - asset: assets/fonts/Inter.ttf
          weight: 600
        - asset: assets/fonts/Inter.ttf
          weight: 700
        - asset: assets/fonts/Inter.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
